modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="https://github.com/Ceziak/upgraded/issues"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

displayURL="https://github.com/Ceziak/upgraded"
authors="Ceziak"

description='''
Allows you to upgrade ur fav low-tier tools to higher qualities!
'''


[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
reason="UPGRADED! requires NeoForge."
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"


[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
reason="UPGRADED! is made for Minecraft 1.21.1."
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"